"""
Alembic Migration Script Template
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf5756081bc'
down_revision = 'cf1c10905a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add VALIDATING status to modelstatus enum
    # PostgreSQL doesn't support BEFORE with IF NOT EXISTS, so we just add to the end
    op.execute("ALTER TYPE modelstatus ADD VALUE IF NOT EXISTS 'validating'")
    
    # Add validation_error column
    op.add_column('models', sa.Column('validation_error', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'validation_error')
    # ### end Alembic commands ###
