"""
Alembic Migration Script Template
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acd4d88a1c50'
down_revision = '543e55c26b39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add API workflow features to workflows table
    op.add_column('workflows', sa.Column('api_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workflows', sa.Column('api_rate_limit_override', sa.Integer(), nullable=True))
    
    # Create workflow_api_calls table for tracking API usage
    op.create_table(
        'workflow_api_calls',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('execution_id', sa.Integer(), nullable=True),
        sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('status_code', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_api_calls_id'), 'workflow_api_calls', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_api_calls_workflow_id'), 'workflow_api_calls', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_api_calls_user_time'), 'workflow_api_calls', ['user_id', 'called_at'], unique=False)
    op.create_index(op.f('ix_workflow_api_calls_workflow_time'), 'workflow_api_calls', ['workflow_id', 'called_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove workflow_api_calls table
    op.drop_index(op.f('ix_workflow_api_calls_workflow_time'), table_name='workflow_api_calls')
    op.drop_index(op.f('ix_workflow_api_calls_user_time'), table_name='workflow_api_calls')
    op.drop_index(op.f('ix_workflow_api_calls_workflow_id'), table_name='workflow_api_calls')
    op.drop_index(op.f('ix_workflow_api_calls_id'), table_name='workflow_api_calls')
    op.drop_table('workflow_api_calls')
    
    # Remove API columns from workflows table
    op.drop_column('workflows', 'api_rate_limit_override')
    op.drop_column('workflows', 'api_enabled')
    # ### end Alembic commands ###
