"""
Alembic Migration Script Template
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0077ad8bfac'
down_revision = '2025_12_18_add_user_files'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create app_settings table for persistent counters (if not exists)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'app_settings' not in inspector.get_table_names():
        op.create_table('app_settings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('key', sa.String(length=100), nullable=False),
            sa.Column('value', sa.Text(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
        op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
        
        # Initialize session_auto_increment counter to 1
        op.execute("""
            INSERT INTO app_settings (key, value, description, updated_at)
            VALUES ('session_auto_increment', '1', 'Auto-increment counter for session name tags', NOW())
        """)
    
    # Handle user_files table drop (if exists)
    op.drop_index(op.f('ix_user_files_deleted_cleanup'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_id'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_is_deleted'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_user_folder'), table_name='user_files')
    op.drop_table('user_files')
    
    # Create new enum types (if they don't exist)
    op.execute("DO $$ BEGIN CREATE TYPE predictionmode AS ENUM ('single', 'batch', 'video', 'rtsp'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE predictionstatus AS ENUM ('pending', 'running', 'completed', 'failed'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Alter columns with USING clause for type conversion
    op.execute("ALTER TABLE prediction_jobs ALTER COLUMN mode TYPE predictionmode USING mode::text::predictionmode")
    op.execute("ALTER TABLE prediction_jobs ALTER COLUMN status TYPE predictionstatus USING status::text::predictionstatus")
    
    # Drop old enum types
    op.execute("DROP TYPE IF EXISTS detectionmode")
    op.execute("DROP TYPE IF EXISTS detectionstatus")
    
    # Rename indexes from detection_* to prediction_* (use IF EXISTS to handle cases where already renamed)
    op.execute("DROP INDEX IF EXISTS ix_detection_jobs_creator_id")
    op.execute("DROP INDEX IF EXISTS ix_detection_jobs_id")
    op.execute("DROP INDEX IF EXISTS ix_detection_jobs_project_id")
    op.execute("DROP INDEX IF EXISTS ix_detection_jobs_session_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_jobs_creator_id ON prediction_jobs (creator_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_jobs_id ON prediction_jobs (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_jobs_project_id ON prediction_jobs (project_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_jobs_session_id ON prediction_jobs (session_id)")
    
    op.execute("DROP INDEX IF EXISTS ix_detection_results_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_results_id ON prediction_results (id)")
    
    op.execute("DROP INDEX IF EXISTS ix_detection_sessions_created_at")
    op.execute("DROP INDEX IF EXISTS ix_detection_sessions_creator_id")
    op.execute("DROP INDEX IF EXISTS ix_detection_sessions_id")
    op.execute("DROP INDEX IF EXISTS ix_detection_sessions_project_id")
    op.execute("DROP INDEX IF EXISTS ix_detection_sessions_status")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_sessions_created_at ON prediction_sessions (created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_sessions_creator_id ON prediction_sessions (creator_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_sessions_id ON prediction_sessions (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_sessions_project_id ON prediction_sessions (project_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prediction_sessions_status ON prediction_sessions (status)")
    
    # Create workflow indexes if they don't exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_workflow_executions_id ON workflow_executions (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_workflow_step_executions_id ON workflow_step_executions (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_workflows_id ON workflows (id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop app_settings table
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflow_step_executions_id'), table_name='workflow_step_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_prediction_sessions_status'), table_name='prediction_sessions')
    op.drop_index(op.f('ix_prediction_sessions_project_id'), table_name='prediction_sessions')
    op.drop_index(op.f('ix_prediction_sessions_id'), table_name='prediction_sessions')
    op.drop_index(op.f('ix_prediction_sessions_creator_id'), table_name='prediction_sessions')
    op.drop_index(op.f('ix_prediction_sessions_created_at'), table_name='prediction_sessions')
    op.create_index(op.f('ix_detection_sessions_status'), 'prediction_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_detection_sessions_project_id'), 'prediction_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_detection_sessions_id'), 'prediction_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_detection_sessions_creator_id'), 'prediction_sessions', ['creator_id'], unique=False)
    op.create_index(op.f('ix_detection_sessions_created_at'), 'prediction_sessions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_prediction_results_id'), table_name='prediction_results')
    op.create_index(op.f('ix_detection_results_id'), 'prediction_results', ['id'], unique=False)
    op.drop_index(op.f('ix_prediction_jobs_session_id'), table_name='prediction_jobs')
    op.drop_index(op.f('ix_prediction_jobs_project_id'), table_name='prediction_jobs')
    op.drop_index(op.f('ix_prediction_jobs_id'), table_name='prediction_jobs')
    op.drop_index(op.f('ix_prediction_jobs_creator_id'), table_name='prediction_jobs')
    op.create_index(op.f('ix_detection_jobs_session_id'), 'prediction_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_detection_jobs_project_id'), 'prediction_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_detection_jobs_id'), 'prediction_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_detection_jobs_creator_id'), 'prediction_jobs', ['creator_id'], unique=False)
    
    # Create old enum types
    op.execute("CREATE TYPE detectionmode AS ENUM ('single', 'batch', 'video', 'rtsp')")
    op.execute("CREATE TYPE detectionstatus AS ENUM ('pending', 'running', 'completed', 'failed')")
    
    # Alter columns back with USING clause
    op.execute("ALTER TABLE prediction_jobs ALTER COLUMN status TYPE detectionstatus USING status::text::detectionstatus")
    op.execute("ALTER TABLE prediction_jobs ALTER COLUMN mode TYPE detectionmode USING mode::text::detectionmode")
    
    # Drop new enum types
    op.execute("DROP TYPE IF EXISTS predictionmode")
    op.execute("DROP TYPE IF EXISTS predictionstatus")
    op.create_table('user_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('folder_path', sa.VARCHAR(), server_default=sa.text("'shared'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_system_folder', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_files_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_files_pkey'))
    )
    op.create_index(op.f('ix_user_files_user_folder'), 'user_files', ['user_id', 'folder_path'], unique=False)
    op.create_index(op.f('ix_user_files_is_deleted'), 'user_files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_files_id'), 'user_files', ['id'], unique=False)
    op.create_index(op.f('ix_user_files_deleted_cleanup'), 'user_files', ['is_deleted', 'deleted_at'], unique=False)
    # ### end Alembic commands ###
