"""
Alembic Migration Script Template
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e189e03c757'
down_revision = '18b9a39f6956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip enum type changes (campaign_exports, campaigns) - they're just renames, not structural changes
    
    # Check if api_key column exists
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT column_name FROM information_schema.columns 
        WHERE table_name='models' AND column_name='api_key'
    """))
    api_key_exists = result.fetchone() is not None
    
    if not api_key_exists:
        # Add api_key column to models table
        op.add_column('models', sa.Column('api_key', postgresql.UUID(as_uuid=True), nullable=True))
        
        # Populate existing models with UUIDs
        op.execute("""
            UPDATE models SET api_key = gen_random_uuid() WHERE api_key IS NULL
        """)
        
        # Make api_key non-nullable and unique
        op.alter_column('models', 'api_key', nullable=False)
        op.create_index(op.f('ix_models_api_key'), 'models', ['api_key'], unique=True)
    
    # Check if inference_api_calls table exists
    result = conn.execute(sa.text("""
        SELECT table_name FROM information_schema.tables 
        WHERE table_name='inference_api_calls'
    """))
    table_exists = result.fetchone() is not None
    
    if not table_exists:
        # Create inference_api_calls table
        op.create_table('inference_api_calls',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('model_id', sa.Integer(), nullable=False),
            sa.Column('prediction_job_id', sa.Integer(), nullable=True),
            sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('response_time_ms', sa.Float(), nullable=True),
            sa.Column('status_code', sa.Integer(), nullable=False),
            sa.Column('file_count', sa.Integer(), nullable=True, server_default='1'),
            sa.Column('error_message', sa.String(length=512), nullable=True),
            sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['prediction_job_id'], ['prediction_jobs.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_inference_api_calls_called_at'), 'inference_api_calls', ['called_at'], unique=False)
        op.create_index(op.f('ix_inference_api_calls_model_id'), 'inference_api_calls', ['model_id'], unique=False)
        op.create_index(op.f('ix_inference_api_calls_user_id'), 'inference_api_calls', ['user_id'], unique=False)
    
    # Add other indexes
    op.create_index(op.f('ix_projects_is_system'), 'projects', ['is_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_is_system'), table_name='projects')
    
    # Drop inference_api_calls table
    op.drop_index(op.f('ix_inference_api_calls_user_id'), table_name='inference_api_calls')
    op.drop_index(op.f('ix_inference_api_calls_model_id'), table_name='inference_api_calls')
    op.drop_index(op.f('ix_inference_api_calls_called_at'), table_name='inference_api_calls')
    op.drop_table('inference_api_calls')
    
    # Remove api_key from models
    op.drop_index(op.f('ix_models_api_key'), table_name='models')
    op.drop_column('models', 'api_key')
    # ### end Alembic commands ###
